### PR TITLE
Add chapter param to helpers/scan.py download function.

### PR DESCRIPTION
**Pull request by tenableAndrew**
If you do not pass a valid chapter param to the ScanExportRequest when attempting to export a PDF/HTML file the resulting file will not contain any scan contents. 

I've addressed this in the helpers/scan.py download function and added a few valid constants for  ScanExportRequest.chapters.

### CODE REVIEW

**Comment by tenableAndrew** [comment]
I've also added the code used in an upcoming blog post to this PR, it relies on this fix in order to run successfully.

@paragbaxi wanted to include this in the SDK for those getting started. We can also update this file later with a link back to the blog post once it is live.

**Comment by alanfung** [comment]
I am in the process of porting this. I hope to chat in our weekly tomorrow regarding to the tutorial file and how we should organize them.

**Comment by tenableAndrew** [comment]
Sounds good, thanks!

**Comment by alanfung** [comment]
Port and addressed in PR #38.

**Pull request closed without merging**
